### ISSUE TITLE
ESMM的相关问题

### ISSUE THREAD

**Issue by Zhangxy98** [datawhalechina/torch-rechub#31]
作者你好，我是一个小白，有几个问题想咨询一下，如果您看到受累帮我解答一下，谢谢：
（1）esmm那个模型输出的两个auc分别对应的那个任务？
（2）可以输出每个任务的预测值吗？
（3）输入特征是只能是01吗，连续型数值可以吗？
（4）可以加入其他的评价指标吗？

**Comment by morningsky** [comment]
@Zhangxy98 hi
（1）与论文一样，分别对应ctr和ctcvr，具体可以查看mtl_trainer.py第110-111行。
（2）调用MTLTrainer的predict函数即可输出。
（3）目前按照论文的设定，只输入Sparse特征，不支持连续型（论文中有一个分别将user侧和item侧的特征embedding求和的模块），如果你自己的场景需要加的话也很容易修改：1.删除该模块 2.将获取user和item侧特征embedding的函数，设置squeeze_dim=True，这样可以兼容任意类型的特征。
（4）esmm模型不能，这个就是两个分类任务的联合训练，其他MTL模型可以将回归与分类回合。

**Comment by Zhangxy98** [comment]
> @Zhangxy98 hi （1）与论文一样，分别对应ctr和ctcvr，具体可以查看mtl_trainer.py第110-111行。 （2）调用MTLTrainer的predict函数即可输出。 （3）目前按照论文的设定，只输入Sparse特征，不支持连续型（论文中有一个分别将user侧和item侧的特征embedding求和的模块），如果你自己的场景需要加的话也很容易修改：1.删除该模块 2.将获取user和item侧特征embedding的函数，设置squeeze_dim=True，这样可以兼容任意类型的特征。 （4）esmm模型不能，这个就是两个分类任务的联合训练，其他MTL模型可以将回归与分类回合。

您好，我还有一个问题， cvr和ctr两个网络的输入是否都是全量样本呢？还是cvr是点击样本，ctr是全量样本。因为我看它的那个模型结构图的input是分开的，并没有像MMoE的模型图那种是合并为一个input。

**Comment by Zhangxy98** [comment]
> @Zhangxy98 hi （1）与论文一样，分别对应ctr和ctcvr，具体可以查看mtl_trainer.py第110-111行。 （2）调用MTLTrainer的predict函数即可输出。 （3）目前按照论文的设定，只输入Sparse特征，不支持连续型（论文中有一个分别将user侧和item侧的特征embedding求和的模块），如果你自己的场景需要加的话也很容易修改：1.删除该模块 2.将获取user和item侧特征embedding的函数，设置squeeze_dim=True，这样可以兼容任意类型的特征。 （4）esmm模型不能，这个就是两个分类任务的联合训练，其他MTL模型可以将回归与分类回合。
