### ISSUE TITLE
Mistake in preprocess_ali_ccp.py

### ISSUE THREAD

**Issue by wyhwhy** [datawhalechina/torch-rechub#35]
In Line 81, vocabulary[k][v] should be set to 1 at first to coordinate with Line 90 (which should be >=10, for example). In this case the **TRUE** threshold is 12 now.

**Comment by yinpu** [comment]
@wyhwhy Thanks for noticing this detail, we will fix this mistake.  We appreciate all contributions to improve torch-rechub. Welcome to participate in this project.

**Comment by wyhwhy** [comment]
> @wyhwhy Thanks for noticing this detail, we will fix this mistake. We appreciate all contributions to improve torch-rechub. Welcome to participate in this project.

Thanks for rely
