### ISSUE TITLE
请教关于负采样的问题

### ISSUE THREAD

**Issue by ZoeyChen-lab** [datawhalechina/torch-rechub#51]
以sample_method=0的采样方式为例，在negative_sample()函数里，是随机对item_id进行采样的。这里并没有判断采样的item_id是当前用户的未点击样本。所以想请问如果采样到的item_id正好是该用户历史点击过的样本或者正好是是当前正样本的item_id应该如何处理？在代码的哪一部分进行处理的？这个我可能没有看到，请各位指教~

**Comment by yinpu** [comment]
应该是没有处理。不过一般情况下，用户的未点击样本占很大一部分，采样到用户历史点击过的样本概率很小，对模型影响可能较小，可无需考虑。
